SD_PATH = '/mnt/ams2/'
IMG_SRC_PATH = SD_PATH + 'SD/proc2/'
WAITING_JOBS_FOLDER = SD_PATH + '/CUSTOM_VIDEOS/'
WAITING_JOBS = WAITING_JOBS_FOLDER + 'waiting_jobs.json'
VID_FOLDER = WAITING_JOBS_FOLDER 

HD_VID_SRC_PATH="/mnt/ams2/HD/"