ORG_PATH = '/mnt/ams2/'


IMG_SD_SRC_PATH = ORG_PATH + 'SD/proc2/'
HD_VID_SRC_PATH=  ORG_PATH + 'HD/'

#Store JSON
WAITING_JOBS_FOLDER = ORG_PATH + '/CUSTOM_VIDEOS/'
WAITING_JOBS = WAITING_JOBS_FOLDER + 'waiting_jobs.json'

#Store Vidos
VID_FOLDER = WAITING_JOBS_FOLDER 

