CREATE TABLE IF NOT EXISTS "ml_weather_snaps" (
        "filename"      TEXT,
        "station_id"    TEXT,
        "camera_id"     TEXT,
        "local_datetime_key"    TEXT,
        "ai_final"      TEXT,
        "samples_done"  INT,
        PRIMARY KEY("filename")
        );
CREATE TABLE IF NOT EXISTS "ml_weather_samples" (
        "filename"      TEXT,
        "station_id"    TEXT,
        "camera_id"     TEXT,
        "local_datetime_key"    TEXT,
        "ai_sky_condition"      TEXT,
        "ai_sky_condition_conf" INTEGER,
        "ai_cloud_type" TEXT,
        "ai_cloud_type_conf"    INTEGER,
        "ai_phenom"     TEXT,
        "ai_phenom_conf"        INTEGER,
        "ai_severe"     TEXT,
        "ai_severe_conf"        INTEGER,
        "hm_sky_condition"      TEXT,
        "hm_cloud_type" TEXT,
        "hm_phenom"     TEXT,
        "hm_severe"     TEXT,
        "repo_sync_status"      TEXT,
        PRIMARY KEY("filename")
        );
CREATE TABLE IF NOT EXISTS "weather_conditions" (
        "station_id"    TEXT,
        "local_datetime_key"    TEXT,
        "utc_time_offset"       REAL,
        "sun_status"    TEXT,
        "sun_az"        REAL,
        "sun_el"        REAL,
        "moon_status"   TEXT,
        "moon_az"       REAL,
        "moon_el"       REAL,
        "forecast"      TEXT,
        "actual"        TEXT,
        "ai_final"      TEXT,
        "samples_done"  INT,
        PRIMARY KEY("station_id","local_datetime_key")
      );

CREATE TABLE "metar" (
	"raw_text"	TEXT,
	"station_id"	TEXT,
	"observation_time"	TEXT,
	"latitude"	REAL,
	"longitude"	REAL,
	"elevation_m"	REAL,
	"temp_c"	REAL,
	"dewpoint_c"	REAL,
	"wind_dir_degrees"	REAL,
	"wind_speed_kt"	REAL,
	"wind_gust_kt"	REAL,
	"visibility_statute_mi"	REAL,
	"altim_in_hg"	REAL,
	"sea_level_pressure_mb"	REAL,
	"three_hr_pressure_tendency_mb"	REAL,
	"sky_conditions"	TEXT,
	"pcp3hr_in"	REAL,
	"pcp6hr_in"	REAL,
	"pcp24hr_in"	REAL,
	"precip_in"	REAL,
	"flight_category"	TEXT,
	"metar_type"	TEXT,
	"maxt_c"	REAL,
	"mint_c"	REAL,
	"mint24hr_c"	REAL,
	"maxt24hr_c"	REAL,
	"wx_string"	TEXT,
	PRIMARY KEY("raw_text")
);
