apt-get install -y apt-transport-https
apt-get install -y apt-utils
apt-get install -y automake
apt-get install -y build-essential
apt-get install -y ca-certificates
apt-get install -y cmake
apt-get install -y curl
apt-get install -y ffmpeg
apt-get install -y gfortran
apt-get install -y git
apt-get install -y imagemagick
apt-get install -y libatlas-base-dev
apt-get install -y libavcodec-dev
apt-get install -y libavformat-dev
apt-get install -y libavresample-dev
apt-get install -y libbz2-dev
apt-get install -y libcairo2-dev
apt-get install -y libcfitsio-dev
apt-get install -y libcurl4-openssl-dev
apt-get install -y libdc1394-22
apt-get install -y libdc1394-utils
apt-get install -y libfuse-dev
apt-get install -y libgeos-dev
apt-get install -y libgtk2.0-dev
apt-get install -y libgtk-3-dev
apt-get install -y libjpeg-dev
apt-get install -y libleptonica-dev
apt-get install -y libnetpbm10-dev
apt-get install -y libopencv-dev
apt-get install -y libpng-dev
apt-get install -y libproj-dev
apt-get install -y libssl-dev
apt-get install -y libswscale-dev
apt-get install -y libtbb2 
apt-get install -y libtesseract-dev
apt-get install -y libtiff-dev
apt-get install -y libtool
apt-get install -y libv4l-dev
apt-get install -y libx264-dev
apt-get install -y libxml2-dev
apt-get install -y libxvidcore-dev
apt-get install -y mime-support
apt-get install -y netpbm 
apt-get install -y net-tools
apt-get install -y openssh-server
apt-get install -y pkg-config
apt-get install -y pkg-config 
apt-get install -y python 
apt-get install -y python3
apt-get install -y python3-dev
apt-get install -y python3-mpltoolkits.basemap
apt-get install -y python3-opencv
apt-get install -y python3-pil
apt-get install -y python3-pil.imagetk
apt-get install -y python3-tk
apt-get install -y python-dev
apt-get install -y python-numpy
apt-get install -y python3-pip
apt-get install -y redis-server
apt-get install -y scikit-image
apt-get install -y software-properties-common 
apt-get install -y swig
apt-get install -y sysstat
apt-get install -y tesseract-ocr
apt-get install -y unzip
apt-get install -y vim
apt-get install -y wcslib-dev
apt-get install -y xrdp
apt-get install -y zlib1g
apt-get install -y python-simplejson
apt-get install -y astrometry.net
apt-get install -y ubuntu-gnome-desktop
apt-get install -y gnome-menu-editor
apt-get install -y gnome-panel 
apt-get install -y h264
apt-get install -y vlc 
apt-get install -y libgstreamer1.0-dev
apt-get install -y libgstreamer-plugins-bad1.0-dev
apt-get install -y libgstreamer-plugins-base1.0-dev
apt-get install -y libgstreamer-plugins-good1.0-dev
apt-get install -y sqlite3 
