mkdir /mnt/ams2/SD/
mkdir /mnt/ams2/SD/proc2
mkdir /mnt/ams2/SD/proc2/daytime
mkdir /mnt/ams2/SD/proc2/json
mkdir /mnt/ams2/HD/
mkdir /mnt/ams2/tmp
mkdir /mnt/ams2/cal
mkdir /mnt/ams2/cal/freecal
mkdir /mnt/ams2/cal/hd_images
mkdir /mnt/ams2/cal/
mkdir /mnt/ams2/cal/tmp
mkdir /mnt/ams2/trash
mkdir /mnt/ams2/latest
mkdir /mnt/ams2/CAMS
mkdir /mnt/ams2/CAMS/queue
mkdir /mnt/ams2/stations
mkdir /mnt/ams2/multi_station
mkdir /mnt/ams2/meteors
